// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAA1pl144QE_iL4LxSZCJl32kvgCwAybM',
    appId: '1:963678496618:web:c56f078d2fc4826a7be713',
    messagingSenderId: '963678496618',
    projectId: 'buy-or-sell-c810e',
    authDomain: 'buy-or-sell-c810e.firebaseapp.com',
    storageBucket: 'buy-or-sell-c810e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGzCbb0dnZC7Jwz8GsM-7NSr6yBcAc1BU',
    appId: '1:963678496618:android:65e22534d17ce8567be713',
    messagingSenderId: '963678496618',
    projectId: 'buy-or-sell-c810e',
    storageBucket: 'buy-or-sell-c810e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0O8h3LoPmTOTfTUoiZaU3vMSv8f4ug-A',
    appId: '1:963678496618:ios:feedcd755c2472b27be713',
    messagingSenderId: '963678496618',
    projectId: 'buy-or-sell-c810e',
    storageBucket: 'buy-or-sell-c810e.appspot.com',
    iosClientId: '963678496618-6biq10lom54fitba0s2phtja2uu7vq6n.apps.googleusercontent.com',
    iosBundleId: 'com.sahotech.buyOrSell',
  );
}
